env:
- namespace: "backstage"
  companyname: "ACME Inc"
  gitopsnamespace: "janus-argocd"
  gitopsinfranamespace: "infra-argocd"
  pipelinesnamespace: "janus-pipelines"
  vaultconfignamespace: "vault-config-operator"
  vaultnamespace: "vault"
  gitwebhooknamespace: "gitwebhook-operator"
  janusinstancename: "janus-dev"
  # githubinfraorganization: "janus-idp"
  githubinfraorganization: "redhat-na-ssa"
  githubinfrareponame: "janus-idp-bootstrap"
  githubinfrarevision: "main"
