{{- if .Values.namespaces }}
{{- range $ns := .Values.namespaces }}
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: {{ $.Values.name }}
  labels:
    app: {{ $.Values.name }}
  {{- if not $.Values.ignoreHelmHooks }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "25"
  {{- end }}
  namespace: {{ $ns }}
spec:
  applicationInstanceLabelKey: rht-gitops.com/{{ $ns }}
  {{- if $.Values.argocd_cr }}
  {{- $.Values.argocd_cr | toYaml | trim | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
